'use client';
import React from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { AlertTriangle,ArrowLeft,ExternalLink,MapPin,ShieldCheck,Trophy,Wifi,Car,Clock } from 'lucide-react';
import { Navigation } from '@/components/Navigation';
import { api,normalizeSpot,SpotModel } from '@/lib/api';

export default function SpotDetail(){
  const {slug}=useParams<{slug:string}>();const [spot,setSpot]=React.useState<SpotModel|null>(null);const [alternatives,setAlternatives]=React.useState<SpotModel[]>([]);const [error,setError]=React.useState('');
  React.useEffect(()=>{Promise.all([api.get(`/spots/${slug}`),api.get(`/spots/${slug}/alternatives`)]).then(([detail,alts])=>{const current=normalizeSpot(detail.data.data);setSpot(current);setAlternatives(alts.data.data.map(normalizeSpot));api.post(`/spots/${current.id}/interactions`,{type:'view'}).catch(()=>{});}).catch(()=>setError('Spot not found.'));},[slug]);
  if(error)return <Navigation><div className="p-12 text-center">{error}</div></Navigation>;if(!spot)return <Navigation><div className="p-12 text-center">Loading destination...</div></Navigation>;
  const directions=`https://www.google.com/maps/dir/?api=1&destination=${spot.gpsLat},${spot.gpsLng}`;const trackDirections=()=>api.post(`/spots/${spot.id}/interactions`,{type:'directions'}).catch(()=>{});
  return <Navigation><article className="max-w-4xl mx-auto space-y-6"><Link href="/explore" className="inline-flex gap-2 text-xs font-bold text-[#2D6A4F]"><ArrowLeft className="w-4 h-4"/>Back to Explore</Link><div className="h-72 rounded-3xl overflow-hidden bg-gradient-to-br from-emerald-100 to-amber-100 relative">{spot.imageUrl?<img src={spot.imageUrl} alt={spot.name} className="w-full h-full object-cover"/>:<MapPin className="absolute inset-0 m-auto w-20 h-20 text-[#2D6A4F]/30"/>}</div>
  <section className="bg-white rounded-3xl p-6 md:p-8 border border-[#D5C4AC]/50 space-y-5"><div><div className="flex flex-wrap gap-2 mb-2"><span className="text-[10px] uppercase font-black bg-emerald-50 text-[#2D6A4F] px-2 py-1 rounded">{spot.subcategory.replaceAll('_',' ')}</span>{spot.trustLevel==='lgu_verified'&&<span className="text-[10px] font-black bg-blue-50 text-blue-700 px-2 py-1 rounded flex gap-1"><ShieldCheck className="w-3 h-3"/>LGU verified</span>}<span className="text-[10px] font-black bg-stone-100 px-2 py-1 rounded">{spot.crowdStatus==='estimated_busy'?'Estimated busy':spot.crowdStatus==='unknown'?'Crowd unknown':spot.crowdStatus}</span></div><h1 className="text-3xl md:text-4xl font-black font-serif text-[#582F0E]">{spot.name}</h1><p className="text-sm text-[#837560] mt-2 flex gap-1"><MapPin className="w-4 h-4"/>{spot.address}</p></div>
  {spot.crowdStatus==='estimated_busy'&&<div className="rounded-2xl bg-amber-50 border border-amber-200 p-4 text-sm text-amber-900"><p className="font-black flex gap-2"><AlertTriangle className="w-5 h-5"/>This destination may be busy</p><p className="mt-1">Based on recent JuanderQuest activity—not live occupancy. Consider a similar, lower-pressure destination below.</p></div>}
  <p className="text-sm leading-7 text-[#514532]">{spot.description}</p><div className="grid sm:grid-cols-3 gap-3 text-xs"><div className="bg-[#FAF9F5] p-3 rounded-xl"><Clock className="w-4 h-4 text-[#2D6A4F] mb-1"/>{Object.values(spot.hours)[0]||'Hours unavailable'}</div><div className="bg-[#FAF9F5] p-3 rounded-xl"><Car className="w-4 h-4 text-[#2D6A4F] mb-1"/>{spot.amenities.includes('parking')?'Parking available':'Check local parking'}</div><div className="bg-[#FAF9F5] p-3 rounded-xl"><Wifi className="w-4 h-4 text-[#2D6A4F] mb-1"/>{spot.amenities.join(', ')||'Amenities updating'}</div></div><div className="flex flex-col sm:flex-row gap-3"><a onClick={trackDirections} href={directions} target="_blank" rel="noreferrer" className="flex-1 bg-[#2D6A4F] text-white rounded-xl py-3 px-5 text-sm font-black flex justify-center gap-2">Get directions<ExternalLink className="w-4 h-4"/></a>{spot.questId&&<Link href={`/quests/${spot.questId}`} className="flex-1 bg-[#FFB703] text-[#582F0E] rounded-xl py-3 px-5 text-sm font-black flex justify-center gap-2"><Trophy className="w-4 h-4"/>Play this quest</Link>}</div><p className="text-[10px] text-[#837560]">Source: {spot.sourceName}. Crowd level is an app-activity estimate, last updated {spot.crowdUpdatedAt?new Date(spot.crowdUpdatedAt).toLocaleString():'when sufficient activity is available'}.</p></section>
  <section className="space-y-3"><p className="text-xs font-black uppercase tracking-wider text-[#7D5800]">Spread the adventure</p><h2 className="text-2xl font-black font-serif text-[#582F0E]">Similar places nearby</h2>{alternatives.length?<div className="grid md:grid-cols-3 gap-4">{alternatives.map(a=><Link href={`/spots/${a.slug}`} key={a.id} className="bg-white border border-[#D5C4AC]/50 rounded-2xl p-4 hover:shadow-lg"><h3 className="font-black text-[#582F0E]">{a.name}</h3><p className="text-xs text-[#837560] mt-1">{a.municipality} · {a.distanceKm?.toFixed(1)} km</p><div className="mt-3 flex flex-wrap gap-1">{a.recommendationReasons.slice(0,2).map(r=><span key={r} className="text-[10px] rounded bg-emerald-50 text-emerald-800 px-2 py-1">{r}</span>)}</div></Link>)}</div>:<p className="bg-white rounded-2xl p-5 text-sm text-[#514532]">No credible similar alternatives are available within 25 km yet.</p>}</section></article></Navigation>;
}
